### ISSUE TITLE
Changing the title destroys the page's changelog.

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/ep_weave#27]
Changing the title destroys the page's changelog.

Steps to reproduce:

1. Create a page with an appropriate title - in this case `foobar`.
2. Describe some appropriate text in the page.
3. Confirm that the above changes are visible in Time Slider.
4. Write a hash that refers to itself at the end of page - in this case `#foobar`.
5. Edit the first line - in this case `foobar_1`.
6. Click `TITLE CHANGED` button.
7. Confirm that the hash of the last line is rewritten: `#foobar` -> `#foobar_1`
8. The time slider screen shows the following error message.

![image](https://github.com/user-attachments/assets/6cf448f3-7373-4bcc-9eb9-f5e96d5012cf)

**Comment by yacchin1205** [comment]
The following error message appears in the browser's developer console.

I will also look into the https://github.com/ether/etherpad-lite/issues/2802 mentioned in the error message.

```
Error: curSplice[sline] not populated, actual curSplice contents is [0,2,null]. Possibly related to https://github.com/ether/etherpad-lite/issues/2802
    at zs.insert (timeSliderBootstrap-lGThiY57ZvA.min.js:8:2935)
    at Z.mutateTextLines (timeSliderBootstrap-lGThiY57ZvA.min.js:11:322)
    at p (timeSliderBootstrap-lGThiY57ZvA.min.js:58:1464)
    at E (timeSliderBootstrap-lGThiY57ZvA.min.js:58:2882)
    at Array._ (timeSliderBootstrap-lGThiY57ZvA.min.js:58:5653)
    at p (timeSliderBootstrap-lGThiY57ZvA.min.js:57:9618)
    at _ (timeSliderBootstrap-lGThiY57ZvA.min.js:57:10488)
    at HTMLButtonElement.<anonymous> (timeSliderBootstrap-lGThiY57ZvA.min.js:57:13056)
    at HTMLButtonElement.dispatch (timeSliderBootstrap-lGThiY57ZvA.min.js:1:51325)
    at he.handle (timeSliderBootstrap-lGThiY57ZvA.min.js:1:49256)
```

```
Uncaught TypeError: Cannot read properties of undefined (reading 'substring')
    at zs.insert (timeSliderBootstrap-lGThiY57ZvA.min.js:8:3191)
    at Z.mutateTextLines (timeSliderBootstrap-lGThiY57ZvA.min.js:11:322)
    at p (timeSliderBootstrap-lGThiY57ZvA.min.js:58:1464)
    at E (timeSliderBootstrap-lGThiY57ZvA.min.js:58:2882)
    at Array._ (timeSliderBootstrap-lGThiY57ZvA.min.js:58:5653)
    at p (timeSliderBootstrap-lGThiY57ZvA.min.js:57:9618)
    at _ (timeSliderBootstrap-lGThiY57ZvA.min.js:57:10488)
    at HTMLButtonElement.<anonymous> (timeSliderBootstrap-lGThiY57ZvA.min.js:57:13056)
    at HTMLButtonElement.dispatch (timeSliderBootstrap-lGThiY57ZvA.min.js:1:51325)
    at he.handle (timeSliderBootstrap-lGThiY57ZvA.min.js:1:49256)
```

**Comment by yacchin1205** [comment]
After trying several different operations, I was able to confirm that importing plain text would also cause a similar error.

1. Create a Pad
2. Input some texts to the Pad
3. Import plain text - in this case [0a5df7eb-7fa7-4619-ab46-6a5a2b9dbdcc.txt](https://github.com/user-attachments/files/16725488/0a5df7eb-7fa7-4619-ab46-6a5a2b9dbdcc.txt)

The following error is output.

```
Error: curSplice[sline] not populated, actual curSplice contents is [0,5,"foobar_2\n","\n","sample\n",null]. Possibly related to https://github.com/ether/etherpad-lite/issues/2802
    at zs.insert (timeSliderBootstrap-lGThiY57ZvA.min.js:8:2935)
    at Z.mutateTextLines (timeSliderBootstrap-lGThiY57ZvA.min.js:11:322)
    at p (timeSliderBootstrap-lGThiY57ZvA.min.js:58:1464)
    at E (timeSliderBootstrap-lGThiY57ZvA.min.js:58:2882)
    at D (timeSliderBootstrap-lGThiY57ZvA.min.js:58:2943)
    at Object.handleResponse (timeSliderBootstrap-lGThiY57ZvA.min.js:58:4692)
    at Object.handleSocketResponse (timeSliderBootstrap-lGThiY57ZvA.min.js:58:4258)
    at Object.handleMessageFromServer (timeSliderBootstrap-lGThiY57ZvA.min.js:58:5362)
    at xs.<anonymous> (timeSliderBootstrap-lGThiY57ZvA.min.js:58:6939)
    at rt.emit (timeSliderBootstrap-lGThiY57ZvA.min.js:56:44881)
```

```
timeSliderBootstrap-lGThiY57ZvA.min.js:8 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')
    at zs.insert (timeSliderBootstrap-lGThiY57ZvA.min.js:8:3191)
    at Z.mutateTextLines (timeSliderBootstrap-lGThiY57ZvA.min.js:11:322)
    at p (timeSliderBootstrap-lGThiY57ZvA.min.js:58:1464)
    at E (timeSliderBootstrap-lGThiY57ZvA.min.js:58:2882)
    at D (timeSliderBootstrap-lGThiY57ZvA.min.js:58:2943)
    at Object.handleResponse (timeSliderBootstrap-lGThiY57ZvA.min.js:58:4692)
    at Object.handleSocketResponse (timeSliderBootstrap-lGThiY57ZvA.min.js:58:4258)
    at Object.handleMessageFromServer (timeSliderBootstrap-lGThiY57ZvA.min.js:58:5362)
    at xs.<anonymous> (timeSliderBootstrap-lGThiY57ZvA.min.js:58:6939)
    at rt.emit (timeSliderBootstrap-lGThiY57ZvA.min.js:56:44881)
```
